### ISSUE TITLE
Create Firestore Index for travel vertical

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/mango_backend#204]
We already had it on nightly. Now we need it on prod.
- Collection ID:
publish
- Fields indexed:
tag Ascending publish_timestamp Descending
- Query scope	
Collection

or just enter this link:
https://console.firebase.google.com/v1/r/project/zerda-dcf76/firestore/indexes?create_composite=Cktwcm9qZWN0cy96ZXJkYS1kY2Y3Ni9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvcHVibGlzaC9pbmRleGVzL18QARoHCgN0YWcQARoVChFwdWJsaXNoX3RpbWVzdGFtcBACGgwKCF9fbmFtZV9fEAI

**Comment by Daisy-pliu** [comment]
Env: prod
Setup index is done on Firestore.
