### ISSUE TITLE
Valid openUrl and valid deep link all exists -> can't send message

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/mango_backend#254]
Users only can fill one of the destination columns ( pushOpneUrl, pushDeeplink, push Command), and then they can send a message successfully.

**Comment by cnevinc** [comment]
per discussion. We only allow one of pushOpneUrl, pushDeeplink, push Command.

**Comment by Daisy-pliu** [comment]
verify: ✅
it correctly shows "choose either openUrl or deeplink"
