### ISSUE TITLE
Test invalid OpenUrl Link

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/mango_backend#255]
TC4
Case 1) https:/// facebook.com
Case 2)  https://facebook.com[space]
Case 3) [space]https://facebook.com
Case 1,2,3 -> open tab with facebook page 
I think we ask Evan to fix a similar condition on Firebase. We can ask him about this. The link bug about space.

**Comment by cnevinc** [comment]
per discussion, I should remove the space in the beginning and the end of the URL

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 0.30
case 1) deeplink with space : ✅
case 2)OpenUrl with space : ✅
case 3) Impage url with space : ✅
