### ISSUE TITLE
[Deploy] Production - Pub/sub & Admin console

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/mango_backend#260]
1. setup pub/sub subscription topic so cloud run can notify the change and start taking action
2. Deploy Admin console

**Comment by Daisy-pliu** [comment]
Pub/sub config is all done.
we can deploy app engine anytime.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : prod-0.30
verify with Admin console API test and database testing
