### ISSUE TITLE
[Deploy] Production - Android front end 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/mango_backend#263]
Need to confirm with @cnevinc . Nevin will merge to nightly and merge to master automatically?

**Comment by Daisy-pliu** [comment]
verify : ✅
deployed 0.31.1 on prodcution 
![Screen Shot 2020-06-11 at 11 03 00 AM](https://user-images.githubusercontent.com/44990878/84341282-4d362800-abd5-11ea-877b-83098eebb10e.png)
