### ISSUE TITLE
Add end to end tests

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/mango_backend#94]
sanity check after deployment. 
It also needs to remove the data it creates during the sanity check

https://github.com/mozilla-tw/mango_backend/wiki/Reward-Service-Integration-Test

**Comment by cnevinc** [comment]
I've completed a version using Postman.
@Daisy-pliu had helped put it in Stable workflow

**Comment by Daisy-pliu** [comment]
It is on staging now. Whenever we deploy to staging env, it will run API end-to-end test.
<img width="1672" alt="Screen Shot 2019-12-26 at 2 40 13 PM" src="https://user-images.githubusercontent.com/44990878/71462257-be338000-27ed-11ea-8c31-c8638b6c2283.png">
